Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
novoAso: Ocorreu um erro: admin
novoAso: Ocorreu um erro: admin
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
novoAso: Ocorreu um erro: admin
novoAso: Ocorreu um erro: admin
novoAso: Ocorreu um erro: admin
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /users/assets/favicon.ico
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /agendamentos/
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /listaAsos/
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py", line 118, in listaAsos
    return render(request, 'listaAsos.html', {'asos': asos})
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lista_asos_admin' with no arguments not found. 1 pattern(s) tried: ['listaAsosAdmin/(?P<asoId>[0-9]+)\\Z']
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /quemSomos/
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /quemSomos/
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /quemSomos/
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py", line 31, in quemSomos
    return render(request, 'quemsomos.html')
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: quemsomos.html
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /quemSomos/assets/favicon.ico
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /servicos/assets/favicon.ico
Internal Server Error: /servicos/
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py", line 34, in servicos
    return render(request, 'servicos.html')
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'download_aso' with arguments '('',)' not found. 1 pattern(s) tried: ['downloadAso/(?P<asoId>[0-9]+)\\Z']
Not Found: /servicos/back()
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /contato/assets/favicon.ico
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py", line 29, in base
    return render(request, 'home.html')
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'quemSomos' not found. 'quemSomos' is not a valid view function or pattern name.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /ini/
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py", line 29, in ini
    return render(request, 'ini.html')
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static', expected 'endblock'. Did you forget to register or load this tag?
Internal Server Error: /ini/
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py", line 29, in ini
    return render(request, 'ini.html')
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static', expected 'endblock'. Did you forget to register or load this tag?
Not Found: /ini/assets/favicon.ico
Not Found: /ini/outra_pagina.html
/home/marcelo/Documentos/app/apphigiseg/higiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /home/assets/favicon.ico
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'marcelosferreira.pythonanywhere.com'. You may need to add 'marcelosferreira.pythonanywhere.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/marcelosferreira/.virtualenvs/venvapphigiseg/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelosferreira/.virtualenvs/venvapphigiseg/lib/python3.8/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/marcelosferreira/.virtualenvs/venvapphigiseg/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/marcelosferreira/.virtualenvs/venvapphigiseg/lib/python3.8/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'marcelosferreira.pythonanywhere.com'. You may need to add 'marcelosferreira.pythonanywhere.com' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'marcelosferreira.pythonanywhere.com'. You may need to add 'marcelosferreira.pythonanywhere.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/marcelosferreira/.virtualenvs/venvapphigiseg/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelosferreira/.virtualenvs/venvapphigiseg/lib/python3.8/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/marcelosferreira/.virtualenvs/venvapphigiseg/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/marcelosferreira/.virtualenvs/venvapphigiseg/lib/python3.8/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'marcelosferreira.pythonanywhere.com'. You may need to add 'marcelosferreira.pythonanywhere.com' to ALLOWED_HOSTS.
Bad Request: /higiseg-app/admin
Not Found: /home/assets/favicon.ico
Not Found: /contato/assets/favicon.ico
Not Found: /login/assets/favicon.ico
Not Found: /listaEmpresasAdmin/assets/favicon.ico
Not Found: /favicon.ico
Not Found: /home/assets/favicon.ico
Not Found: /login/assets/favicon.ico
Ocorreu um erro: Senha e/ou user inválido
Forbidden (CSRF token from POST incorrect.): /login/
OSError: write error
Not Found: /quemSomos/assets/favicon.ico
Not Found: /contato/assets/favicon.ico
Not Found: /servicos/assets/favicon.ico
Not Found: /listaEmpresasAdmin/assets/favicon.ico
Not Found: /listaAsosAdmin/assets/favicon.ico
Not Found: /novoAso/assets/favicon.ico
Not Found: /listaAgendamentosAdmin/assets/favicon.ico
Not Found: /favicon.ico
Not Found: /home/assets/favicon.ico
Not Found: /login/assets/favicon.ico
Not Found: /listaEmpresasAdmin/assets/favicon.ico
Not Found: /novoAso/assets/favicon.ico
Not Found: /listaAgendamentosAdmin/assets/favicon.ico
Not Found: /quemSomos/assets/favicon.ico
Not Found: /servicos/assets/favicon.ico
Not Found: /contato/assets/favicon.ico
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /listaEmpresasAdmin/
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /home/
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'progressivo_web_app_meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marcelo/Documentos/app/apphigiseg/higiseg/views.py", line 32, in base
    return render(request, 'home.html')
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/marcelo/.local/lib/python3.8/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 5: 'progressivo_web_app_meta'. Did you forget to register or load this tag?
Not Found: /home/static/images/icon-160x160.png
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /home/static/icon-160x160.png
/home/marcelo/Documentos/app/apphigiseg/apphigiseg/settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /home/static/assets/icon-160x160.png
